/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.goit.app;

import com.google.gson.Gson;

public class App {

    public static void main(String[] args) {

        User user = new User();
        user.setName("Vadim");
        user.setSurname("Batyashov");
        String json = new Gson().toJson(user);
        System.out.println(json);
    }
}
